---
- name: open http service
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: open https service
  firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- name:
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
