---
 - name: using loop with dict
   hosts: all
   vars:
     emp:
       - name: arihant
         dept: linux admin

       - name: manan
         dept: devops

       - name: pawan
         dept: cloud engg.
   tasks:
     - name: generate a file
       template:
         src: emp.j2
         dest: /employee.txt
