---
 - name: variable practice
   hosts: all
   vars:
     usr: rohit
     dir: /rohit
   tasks:
     - name: create user mohit
       user:
         name: "{{usr}}"
         state: present

     - name : create directory
       file:
         path: "{{ dir  }}"
         state: directory
