---
- name: simple loop example
  hosts: all
  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - mariadb-server
        - ftp

