---
 - name: enterying user details using loop
   hosts: all
   vars:
     students:
       - pawan
       - kushal
       - tanmay
       - arihant
       - manan
   tasks:
     - name: copy template
       template:
         src: users.j2
         dest: /users.txt
